version: '3'
services:
  azure-vote-back:
    build: ./azure-vote-mysql
    image: azure-vote-back
    container_name: azure-vote-back
    deploy:
      resources:
        limits:
          cpus: '0.70'
        reservations:
          cpus: '0.25'
    sysctls:
      net.core.somaxconn: '511'
    security_opt:
      - seccomp:unconfined
    restart: always
    environment:
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: Password12
      MYSQL_DATABASE: azurevote
      MYSQL_ROOT_PASSWORD: Password12
    ports:
        - "3306:3306"
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"
  azure-vote-front:
    build: ./azure-vote
    depends_on:
        - azure-vote-back
    image: azure-vote-front
    container_name: azure-vote-front
    restart: always
    environment:
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: Password12
      MYSQL_DATABASE: azurevote
      MYSQL_HOST: azure-vote-back
    ports:
        - "8080:80"
    logging:
      driver: json-file
      options:
        max-size: "200k"
        max-file: "10"